server:
  port: 5001
spring:
  application:
    name: ATC-BE-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: ATC-BE-MONTECARLO
          uri: http://localhost:5002
          predicates:
            - Path=/atc-be-montecarlo/**
        - id: ATC-BE-OBJECT-DETECTION
          uri: http://localhost:5003
          predicates:
            - Path=/atc-be-object-detection/**
#logging:
#  level:
#    reactor:
#      netty: INFO
#    org:
#      springframework:
#        cloud:
#          gateway: TRACE